import { createReducer } from '@reduxjs/toolkit';
import { projectsActions } from './projects';
import { sprintsActions } from './sprints';
import { tasksActions } from './tasks';

const {
  getProjectsRequest,
  getProjectsSuccess,
  getProjectsError,
  addProjectRequest,
  addProjectSuccess,
  addProjectError,
  deleteProjectRequest,
  deleteProjectSuccess,
  deleteProjectError,
  editProjectRequest,
  editProjectSuccess,
  editProjectError,
  addTeammateRequest,
  addTeammateSuccess,
  addTeammateError,
} = projectsActions;

const {
  getSprintsRequest,
  getSprintsSuccess,
  getSprintsError,
  addSprintRequest,
  addSprintSuccess,
  addSprintError,
  deleteSprintRequest,
  deleteSprintSuccess,
  deleteSprintError,
  editSprintRequest,
  editSprintSuccess,
  editSprintError,
} = sprintsActions;

const {
  getTasksRequest,
  getTasksSuccess,
  getTasksError,
  addTaskRequest,
  addTaskSuccess,
  addTaskError,
  deleteTaskRequest,
  deleteTaskSuccess,
  deleteTaskError,
  editTaskRequest,
  editTaskSuccess,
  editTaskError,
  addTaskHoursRequest,
  addTaskHoursSuccess,
  addTaskHoursError,
} = tasksActions;

const errorReducer = createReducer('', {
  [getProjectsRequest]: () => '',
  [getProjectsSuccess]: () => '',
  [getProjectsError]: (_, payload) => payload,
  [addProjectRequest]: () => '',
  [addProjectSuccess]: () => '',
  [addProjectError]: (_, payload) => payload,
  [deleteProjectRequest]: () => '',
  [deleteProjectSuccess]: () => '',
  [deleteProjectError]: (_, payload) => payload,
  [editProjectRequest]: () => '',
  [editProjectSuccess]: () => '',
  [editProjectError]: (_, payload) => payload,
  [addTeammateRequest]: () => '',
  [addTeammateSuccess]: () => '',
  [addTeammateError]: (_, payload) => payload,
  [getSprintsRequest]: () => true,
  [getSprintsSuccess]: () => '',
  [getSprintsError]: (_, payload) => payload,
  [addSprintRequest]: () => '',
  [addSprintSuccess]: () => '',
  [addSprintError]: (_, payload) => payload,
  [deleteSprintRequest]: () => '',
  [deleteSprintSuccess]: () => '',
  [deleteSprintError]: (_, payload) => payload,
  [editSprintRequest]: () => '',
  [editSprintSuccess]: () => '',
  [editSprintError]: (_, payload) => payload,
  [getTasksRequest]: () => '',
  [getTasksSuccess]: () => '',
  [getTasksError]: (_, payload) => payload,
  [addTaskRequest]: () => '',
  [addTaskSuccess]: () => '',
  [addTaskError]: (_, payload) => payload,
  [deleteTaskRequest]: () => '',
  [deleteTaskSuccess]: () => '',
  [deleteTaskError]: (_, payload) => payload,
  [editTaskRequest]: () => '',
  [editTaskSuccess]: () => '',
  [editTaskError]: (_, payload) => payload,
  [addTaskHoursSuccess]: () => '',
  [addTaskHoursRequest]: () => '',
  [addTaskHoursError]: (_, payload) => payload,
});

export default errorReducer;
